In [1]:
import requests
import pandas as pd
import pytz
import os
from dotenv import load_dotenv

In [2]:
load_dotenv()

cities = [
    "Madrid","Valencia","Alicante","Almería","Granada","Jaén","Málaga","Córdoba",
    "Cádiz","Huelva","Sevilla","Badajoz","Cáceres","Albacete","Toledo","Salamanca",
    "Castellón de la Plana","Barcelona","Tarragona","Gerona","Vitoria-Gasteiz","Oviedo",
    "Ávila","Burgos","Santander","Ciudad Real","Cuenca","Guadalajara","San Sebastian","Huesca",
    "Palma","La Coruña","Logroño","Las Palmas de Gran Canaria","León","Lérida",
    "Lugo", "Murcia","Pamplona","Orense","Palencia", "Pontevedra","Segovia","Soria",
    "Santa Cruz de Tenerife","Teruel","Valladolid","Bilbao","Zamora","Zaragoza"
]

url = "https://api.openweathermap.org/data/2.5/weather?q={city},ES&units=metric&appid={API}"
api_key = os.getenv("OPEN_WEATHER_API_KEY")

json_list = []

for city in cities:
    # Formatear la URL con el nombre de la ciudad y la clave de API
    url_city = url.format(city=city, API=api_key)
    
    # Realizar la solicitud GET a la API
    response = requests.get(url_city)
    
    # Procesar la respuesta de la API
    if response.status_code == 200:
        # La solicitud fue exitosa, procesar los datos de la respuesta
        data_weather = response.json()
        # Añades a la lista
        json_list.append(data_weather)
        
    else:
        # Hubo un error en la solicitud, mostrar el código de estado
        print(f"Error en la solicitud para {city}. Código de estado: {response.status_code}")
        
df_norm = [pd.json_normalize(json) for json in json_list]

df_final = pd.concat(df_norm, ignore_index=True)

In [3]:
df_final

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,...,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,main.sea_level,main.grnd_level,wind.gust
0,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262500,7200,3117735,Madrid,200,-3.7026,40.4165,...,0,20,2.0,2007545.0,ES,1689224120,1689277516,NaN,NaN,NaN
1,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262542,7200,2509951,Valencia,200,-0.8333,39.3333,...,91,19,2.0,2008731.0,ES,1689223625,1689276633,1016.0,976.0,4.33
2,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262147,7200,2521978,Alicante,200,-0.4815,38.3452,...,90,75,1.0,6391.0,ES,1689223712,1689276378,NaN,NaN,NaN
3,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262674,7200,2521883,Almeria,200,-2.3333,37.1667,...,115,0,1.0,6393.0,ES,1689224353,1689276625,1017.0,933.0,3.80
4,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262376,7200,2517115,Granada,200,-3.2500,37.2500,...,285,1,2.0,2008325.0,ES,1689224560,1689276859,1017.0,893.0,8.34
5,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262638,7200,2516394,Jaen,200,-3.5000,38.0000,...,269,2,2.0,2031551.0,ES,1689224495,1689277043,1014.0,938.0,7.44
6,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262610,7200,2514256,Málaga,200,-4.4203,36.7202,...,130,20,2.0,2082955.0,ES,1689224927,1689277053,NaN,NaN,NaN
7,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262676,7200,2519239,Cordoba,200,-4.8333,38.0000,...,190,0,1.0,6394.0,ES,1689224815,1689277363,NaN,NaN,NaN
8,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262676,7200,2520597,Cadiz,200,-5.7500,36.5000,...,260,0,2.0,2012910.0,ES,1689225282,1689277336,1015.0,990.0,3.34
9,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262677,7200,2516547,Province of Huelva,200,-7.0000,37.6667,...,287,0,2.0,2017029.0,ES,1689225391,1689277827,1014.0,1002.0,2.97
10,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262531,7200,2510911,Seville,200,-5.9761,37.3824,...,0,0,2.0,2011488.0,ES,1689225192,1689277535,NaN,NaN,NaN
11,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262678,7200,2521419,Badajoz,200,-6.1667,38.6667,...,296,3,NaN,NaN,ES,1689225022,1689277797,1014.0,973.0,4.15
12,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262678,7200,2520610,Caceres,200,-6.3748,39.5220,...,286,6,NaN,NaN,ES,1689224922,1689277996,1014.0,979.0,3.68
13,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262586,7200,2522257,Albacete,200,-2.0000,38.8333,...,0,0,1.0,6390.0,ES,1689223992,1689276826,NaN,NaN,NaN
14,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262511,7200,2510407,Toledo,200,-4.0000,39.8333,...,305,2,2.0,2035406.0,ES,1689224296,1689277482,NaN,NaN,6.07
15,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262679,7200,3111107,Salamanca,200,-6.0000,40.8333,...,291,4,2.0,2084135.0,ES,1689224594,1689278144,1016.0,929.0,5.74
16,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262669,7200,2519752,Castellón de la Plana,200,-0.0333,39.9833,...,106,17,2.0,2010917.0,ES,1689223317,1689276557,1017.0,1014.0,2.94
17,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262388,7200,3128760,Barcelona,200,2.1590,41.3888,...,190,0,2.0,18549.0,ES,1689222531,1689276291,NaN,NaN,NaN
18,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262681,7200,3108287,Tarragona,200,1.2490,41.1290,...,210,0,1.0,6427.0,ES,1689222799,1689276460,NaN,NaN,NaN
19,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262681,7200,3121456,Girona,200,2.8249,41.9831,...,160,40,2.0,2018885.0,ES,1689222257,1689276245,NaN,NaN,NaN
20,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262546,7200,3104499,Vitoria-Gasteiz,200,-2.6667,42.8500,...,20,75,2.0,2081592.0,ES,1689223406,1689277733,NaN,NaN,NaN
21,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262682,7200,3114711,Oviedo,200,-5.8448,43.3603,...,13,35,2.0,2032169.0,ES,1689224066,1689278598,NaN,NaN,6.71
22,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262683,7200,3129136,Ávila,200,-4.7000,40.6500,...,10,5,2.0,2009026.0,ES,1689224316,1689277798,NaN,NaN,4.02
23,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262510,7200,3127460,Burgos,200,-3.7079,42.3394,...,360,20,1.0,6396.0,ES,1689223757,1689277881,NaN,NaN,NaN
24,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262624,7200,3109718,Santander,200,-3.8044,43.4647,...,60,20,2.0,2008268.0,ES,1689223554,1689278130,NaN,NaN,8.49
25,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262684,7200,2519401,Ciudad Real,200,-4.0000,39.0000,...,256,6,2.0,2009884.0,ES,1689224444,1689277335,NaN,NaN,6.71
26,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262685,7200,2519034,Cuenca,200,-2.0000,40.0000,...,246,2,NaN,NaN,ES,1689223786,1689277032,1016.0,895.0,6.24
27,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262685,7200,3121070,Guadalajara,200,-3.1667,40.6333,...,234,13,2.0,2025414.0,ES,1689223951,1689277427,1015.0,939.0,4.73
28,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262685,7200,3110044,San Sebastian,200,-1.9750,43.3128,...,10,40,2.0,2010406.0,ES,1689223146,1689277660,NaN,NaN,NaN
29,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262400,7200,3120514,Huesca,200,-0.4087,42.1362,...,240,40,2.0,86616.0,ES,1689223004,1689277050,NaN,NaN,NaN
30,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262529,7200,2512989,Palma de Mallorca,200,2.6502,39.5694,...,60,0,2.0,2004014.0,ES,1689222747,1689275839,NaN,NaN,NaN
31,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262454,7200,3119841,A Coruña,200,-8.3960,43.3713,...,340,0,2.0,2002597.0,ES,1689224676,1689279213,NaN,NaN,NaN
32,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262647,7200,3118150,Logroño,200,-2.4500,42.4667,...,260,20,1.0,6418.0,ES,1689223430,1689277605,NaN,NaN,NaN
33,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262589,3600,2515270,Las Palmas de Gran Canaria,200,-15.4134,28.0997,...,20,0,2.0,47680.0,ES,1689228809,1689278448,NaN,NaN,NaN
34,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262687,7200,3118528,Leon,200,-6.0000,42.6667,...,284,54,1.0,6415.0,ES,1689224243,1689278496,1017.0,898.0,5.27
35,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262688,7200,3118514,Lleida,200,0.6167,41.6167,...,230,0,2.0,19264.0,ES,1689222858,1689276704,NaN,NaN,NaN
36,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262389,7200,3117813,Lugo,200,-7.5000,43.0000,...,266,66,2.0,2001961.0,ES,1689224536,1689278922,NaN,NaN,3.14
37,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262533,7200,2513413,Murcia,200,-1.5000,38.0000,...,110,0,1.0,6425.0,ES,1689224015,1689276564,1016.0,977.0,7.44
38,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262510,7200,3114472,Pamplona,200,-1.6432,42.8169,...,320,20,1.0,6417.0,ES,1689223166,1689277481,NaN,NaN,NaN
39,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000,1689262689,7200,3114965,Ourense,200,-7.8500,42.3333,...,278,99,2.0,2021300.0,ES,1689224753,1689278874,1017.0,986.0,2.94
40,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262607,7200,3114530,Palencia,200,-4.5000,42.4167,...,260,76,2.0,96662.0,ES,1689223932,1689278087,1016.0,925.0,4.58
41,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000,1689262689,7200,3113209,Pontevedra,200,-8.6444,42.4310,...,268,99,1.0,6440.0,ES,1689224924,1689279084,1019.0,1017.0,2.49
42,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262510,7200,3109254,Segovia,200,-4.0000,41.1667,...,276,29,2.0,2008767.0,ES,1689224052,1689277726,1016.0,914.0,6.31
43,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262690,7200,3108680,Soria,200,-2.6667,41.6667,...,273,73,2.0,2044140.0,ES,1689223637,1689277501,1016.0,900.0,7.06
44,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1689262690,3600,2511174,Santa Cruz de Tenerife,200,-16.2546,28.4682,...,0,40,2.0,2079291.0,ES,1689228963,1689278698,1018.0,1013.0,7.54
45,"[{'id': 801, 'main': 'Clouds', 'description': ...",stations,10000,1689262539,7200,3108125,Teruel,200,-0.6667,40.6667,...,40,20,NaN,NaN,ES,1689223345,1689276834,1017.0,872.0,8.95
46,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262503,7200,3106671,Valladolid,200,-4.6667,41.5833,...,275,55,2.0,203198.0,ES,1689224133,1689277965,NaN,NaN,5.80
47,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262647,7200,3128026,Bilbao,200,-2.9253,43.2627,...,80,75,2.0,2038329.0,ES,1689223384,1689277878,NaN,NaN,2.24
48,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1689262691,7200,3104342,Zamora,200,-5.7500,41.5000,...,261,79,NaN,NaN,ES,1689224409,1689278209,1016.0,946.0,5.34
49,"[{'id': 800, 'main': 'Clear', 'description': '...",stations,10000,1689262674,7200,3104324,Zaragoza,200,-0.8773,41.6561,...,300,0,2.0,2003310.0,ES,1689223209,1689277070,NaN,NaN,NaN

In [4]:
df_final.columns

Index(['weather', 'base', 'visibility', 'dt', 'timezone', 'id', 'name', 'cod',
       'coord.lon', 'coord.lat', 'main.temp', 'main.feels_like',
       'main.temp_min', 'main.temp_max', 'main.pressure', 'main.humidity',
       'wind.speed', 'wind.deg', 'clouds.all', 'sys.type', 'sys.id',
       'sys.country', 'sys.sunrise', 'sys.sunset', 'main.sea_level',
       'main.grnd_level', 'wind.gust'],
      dtype='object')

In [5]:
# Split de la columna weather en subcolumnas

df_final[['weather_id','weather_main','weather_description','weather_icon']] = df_final['weather'].apply(
    lambda x: pd.Series([x[0]['id'],x[0]['main'],x[0]['description'],x[0]['icon']])
    )

# Eliminamos la columna weather que ya no nos hace falta
df_final = df_final.drop('weather', axis=1)

# Ordenamos

column_orden = ['weather_id', 'weather_main','weather_description', 'weather_icon', 
 'base', 'visibility', 'dt', 'timezone', 'id', 'name', 'cod',
 'coord.lon', 'coord.lat', 'main.temp', 'main.feels_like',
 'main.temp_min', 'main.temp_max', 'main.pressure', 'main.humidity',
 'wind.speed', 'wind.deg', 'clouds.all', 'sys.type', 'sys.id',
 'sys.country', 'sys.sunrise', 'sys.sunset', 'main.sea_level',
 'main.grnd_level', 'wind.gust']

df_final = df_final[column_orden]

In [6]:
# Eliminamos las columnas *weather_id* y *weather_icon* ya que son id's internos de Open Weather

df_final = df_final.drop(['weather_id','weather_icon'], axis=1)

In [7]:
# Eliminamos la columna *base* y *cod* ya que es un dato interno de Open Weather

df_final = df_final.drop(['cod','base'],axis=1)

In [8]:
# Eliminamos las columnas *sys.type* y *sys.id* ya que son parámetros internos

df_final = df_final.drop(['sys.type','sys.id'], axis=1)

In [9]:
df_final

,weather_main,weather_description,visibility,dt,timezone,id,name,coord.lon,coord.lat,main.temp,...,main.humidity,wind.speed,wind.deg,clouds.all,sys.country,sys.sunrise,sys.sunset,main.sea_level,main.grnd_level,wind.gust
0,Clouds,few clouds,10000,1689262500,7200,3117735,Madrid,-3.7026,40.4165,33.69,...,20,3.09,0,20,ES,1689224120,1689277516,NaN,NaN,NaN
1,Clouds,few clouds,10000,1689262542,7200,2509951,Valencia,-0.8333,39.3333,27.18,...,47,6.40,91,19,ES,1689223625,1689276633,1016.0,976.0,4.33
2,Clouds,broken clouds,10000,1689262147,7200,2521978,Alicante,-0.4815,38.3452,29.21,...,76,5.66,90,75,ES,1689223712,1689276378,NaN,NaN,NaN
3,Clear,clear sky,10000,1689262674,7200,2521883,Almeria,-2.3333,37.1667,28.88,...,46,4.03,115,0,ES,1689224353,1689276625,1017.0,933.0,3.80
4,Clear,clear sky,10000,1689262376,7200,2517115,Granada,-3.2500,37.2500,34.21,...,11,6.38,285,1,ES,1689224560,1689276859,1017.0,893.0,8.34
5,Clear,clear sky,10000,1689262638,7200,2516394,Jaen,-3.5000,38.0000,38.55,...,6,6.30,269,2,ES,1689224495,1689277043,1014.0,938.0,7.44
6,Clouds,few clouds,10000,1689262610,7200,2514256,Málaga,-4.4203,36.7202,30.17,...,75,5.14,130,20,ES,1689224927,1689277053,NaN,NaN,NaN
7,Clear,clear sky,10000,1689262676,7200,2519239,Cordoba,-4.8333,38.0000,36.75,...,12,3.09,190,0,ES,1689224815,1689277363,NaN,NaN,NaN
8,Clear,clear sky,10000,1689262676,7200,2520597,Cadiz,-5.7500,36.5000,37.29,...,12,4.12,260,0,ES,1689225282,1689277336,1015.0,990.0,3.34
9,Clear,clear sky,10000,1689262677,7200,2516547,Province of Huelva,-7.0000,37.6667,30.58,...,13,3.98,287,0,ES,1689225391,1689277827,1014.0,1002.0,2.97
10,Clear,clear sky,10000,1689262531,7200,2510911,Seville,-5.9761,37.3824,39.86,...,19,2.57,0,0,ES,1689225192,1689277535,NaN,NaN,NaN
11,Clear,clear sky,10000,1689262678,7200,2521419,Badajoz,-6.1667,38.6667,36.80,...,15,3.39,296,3,ES,1689225022,1689277797,1014.0,973.0,4.15
12,Clear,clear sky,10000,1689262678,7200,2520610,Caceres,-6.3748,39.5220,36.64,...,16,3.49,286,6,ES,1689224922,1689277996,1014.0,979.0,3.68
13,Clear,clear sky,10000,1689262586,7200,2522257,Albacete,-2.0000,38.8333,35.45,...,16,1.03,0,0,ES,1689223992,1689276826,NaN,NaN,NaN
14,Clear,clear sky,10000,1689262511,7200,2510407,Toledo,-4.0000,39.8333,34.50,...,20,4.40,305,2,ES,1689224296,1689277482,NaN,NaN,6.07
15,Clear,clear sky,10000,1689262679,7200,3111107,Salamanca,-6.0000,40.8333,29.61,...,19,5.92,291,4,ES,1689224594,1689278144,1016.0,929.0,5.74
16,Clouds,few clouds,10000,1689262669,7200,2519752,Castellón de la Plana,-0.0333,39.9833,29.73,...,61,4.04,106,17,ES,1689223317,1689276557,1017.0,1014.0,2.94
17,Clear,clear sky,10000,1689262388,7200,3128760,Barcelona,2.1590,41.3888,29.40,...,67,6.69,190,0,ES,1689222531,1689276291,NaN,NaN,NaN
18,Clear,clear sky,10000,1689262681,7200,3108287,Tarragona,1.2490,41.1290,28.71,...,60,6.17,210,0,ES,1689222799,1689276460,NaN,NaN,NaN
19,Clouds,scattered clouds,10000,1689262681,7200,3121456,Girona,2.8249,41.9831,28.96,...,58,4.63,160,40,ES,1689222257,1689276245,NaN,NaN,NaN
20,Clouds,broken clouds,10000,1689262546,7200,3104499,Vitoria-Gasteiz,-2.6667,42.8500,23.92,...,63,5.66,20,75,ES,1689223406,1689277733,NaN,NaN,NaN
21,Clouds,scattered clouds,10000,1689262682,7200,3114711,Oviedo,-5.8448,43.3603,23.57,...,69,4.47,13,35,ES,1689224066,1689278598,NaN,NaN,6.71
22,Clear,clear sky,10000,1689262683,7200,3129136,Ávila,-4.7000,40.6500,30.77,...,33,2.24,10,5,ES,1689224316,1689277798,NaN,NaN,4.02
23,Clouds,few clouds,10000,1689262510,7200,3127460,Burgos,-3.7079,42.3394,27.23,...,39,1.54,360,20,ES,1689223757,1689277881,NaN,NaN,NaN
24,Clouds,few clouds,10000,1689262624,7200,3109718,Santander,-3.8044,43.4647,22.45,...,73,6.26,60,20,ES,1689223554,1689278130,NaN,NaN,8.49
25,Clear,clear sky,10000,1689262684,7200,2519401,Ciudad Real,-4.0000,39.0000,36.17,...,18,4.02,256,6,ES,1689224444,1689277335,NaN,NaN,6.71
26,Clear,clear sky,10000,1689262685,7200,2519034,Cuenca,-2.0000,40.0000,31.32,...,17,5.48,246,2,ES,1689223786,1689277032,1016.0,895.0,6.24
27,Clouds,few clouds,10000,1689262685,7200,3121070,Guadalajara,-3.1667,40.6333,33.37,...,19,3.90,234,13,ES,1689223951,1689277427,1015.0,939.0,4.73
28,Clouds,scattered clouds,10000,1689262685,7200,3110044,San Sebastian,-1.9750,43.3128,24.26,...,65,3.09,10,40,ES,1689223146,1689277660,NaN,NaN,NaN
29,Clouds,scattered clouds,10000,1689262400,7200,3120514,Huesca,-0.4087,42.1362,31.70,...,30,3.60,240,40,ES,1689223004,1689277050,NaN,NaN,NaN
30,Clear,clear sky,10000,1689262529,7200,2512989,Palma de Mallorca,2.6502,39.5694,31.55,...,40,8.23,60,0,ES,1689222747,1689275839,NaN,NaN,NaN
31,Clear,clear sky,10000,1689262454,7200,3119841,A Coruña,-8.3960,43.3713,23.70,...,67,4.47,340,0,ES,1689224676,1689279213,NaN,NaN,NaN
32,Clouds,few clouds,10000,1689262647,7200,3118150,Logroño,-2.4500,42.4667,27.72,...,39,2.57,260,20,ES,1689223430,1689277605,NaN,NaN,NaN
33,Clear,clear sky,10000,1689262589,3600,2515270,Las Palmas de Gran Canaria,-15.4134,28.0997,31.64,...,46,13.38,20,0,ES,1689228809,1689278448,NaN,NaN,NaN
34,Clouds,broken clouds,10000,1689262687,7200,3118528,Leon,-6.0000,42.6667,25.89,...,23,3.57,284,54,ES,1689224243,1689278496,1017.0,898.0,5.27
35,Clear,clear sky,10000,1689262688,7200,3118514,Lleida,0.6167,41.6167,33.80,...,35,3.09,230,0,ES,1689222858,1689276704,NaN,NaN,NaN
36,Clouds,broken clouds,10000,1689262389,7200,3117813,Lugo,-7.5000,43.0000,27.17,...,31,2.08,266,66,ES,1689224536,1689278922,NaN,NaN,3.14
37,Clear,clear sky,10000,1689262533,7200,2513413,Murcia,-1.5000,38.0000,31.17,...,50,9.03,110,0,ES,1689224015,1689276564,1016.0,977.0,7.44
38,Clouds,few clouds,10000,1689262510,7200,3114472,Pamplona,-1.6432,42.8169,24.95,...,50,4.63,320,20,ES,1689223166,1689277481,NaN,NaN,NaN
39,Clouds,overcast clouds,10000,1689262689,7200,3114965,Ourense,-7.8500,42.3333,30.44,...,25,2.07,278,99,ES,1689224753,1689278874,1017.0,986.0,2.94
40,Clouds,broken clouds,10000,1689262607,7200,3114530,Palencia,-4.5000,42.4167,28.26,...,23,4.62,260,76,ES,1689223932,1689278087,1016.0,925.0,4.58
41,Clouds,overcast clouds,10000,1689262689,7200,3113209,Pontevedra,-8.6444,42.4310,25.43,...,39,2.35,268,99,ES,1689224924,1689279084,1019.0,1017.0,2.49
42,Clouds,scattered clouds,10000,1689262510,7200,3109254,Segovia,-4.0000,41.1667,29.68,...,23,5.11,276,29,ES,1689224052,1689277726,1016.0,914.0,6.31
43,Clouds,broken clouds,10000,1689262690,7200,3108680,Soria,-2.6667,41.6667,31.73,...,36,5.33,273,73,ES,1689223637,1689277501,1016.0,900.0,7.06
44,Clouds,scattered clouds,10000,1689262690,3600,2511174,Santa Cruz de Tenerife,-16.2546,28.4682,32.40,...,68,5.94,0,40,ES,1689228963,1689278698,1018.0,1013.0,7.54
45,Clouds,few clouds,10000,1689262539,7200,3108125,Teruel,-0.6667,40.6667,25.95,...,38,3.77,40,20,ES,1689223345,1689276834,1017.0,872.0,8.95
46,Clouds,broken clouds,10000,1689262503,7200,3106671,Valladolid,-4.6667,41.5833,30.70,...,32,5.17,275,55,ES,1689224133,1689277965,NaN,NaN,5.80
47,Clouds,broken clouds,10000,1689262647,7200,3128026,Bilbao,-2.9253,43.2627,24.85,...,61,2.24,80,75,ES,1689223384,1689277878,NaN,NaN,2.24
48,Clouds,broken clouds,10000,1689262691,7200,3104342,Zamora,-5.7500,41.5000,31.79,...,22,5.00,261,79,ES,1689224409,1689278209,1016.0,946.0,5.34
49,Clear,clear sky,10000,1689262674,7200,3104324,Zaragoza,-0.8773,41.6561,31.86,...,32,3.60,300,0,ES,1689223209,1689277070,NaN,NaN,NaN

In [10]:
# Define el huso horario GMT+02:00 con horario de verano (DST)
timezone = pytz.timezone('Europe/Amsterdam')

# Pasar columna "dt" de timestap a date

df_final['date'] = df_final['dt'].apply(lambda x: pd.to_datetime(x, unit='s').tz_localize('UTC').tz_convert(timezone).strftime('%Y-%m-%d %H:%M:%S'))

# Borramos columna "dt"

df_final = df_final.drop('dt', axis=1)

In [12]:
# Pasar las columnas sys.sunrise y sys.sunset al horario español UTC

# Define el huso horario GMT+02:00 con horario de verano (DST)
timezone = pytz.timezone('Europe/Amsterdam')

# Convierte el timestamp a formato de fecha y hora en el huso horario especificado
df_final['sunrise'] = df_final['sys.sunrise'].apply(lambda x: pd.to_datetime(x, unit='s').tz_localize('UTC').tz_convert(timezone).strftime('%H:%M:%S'))

df_final['sunset'] = df_final['sys.sunset'].apply(lambda x: pd.to_datetime(x, unit='s').tz_localize('UTC').tz_convert(timezone).strftime('%H:%M:%S'))

# Elinimanos las columnas "sys.sunrise" y "sys.sunset"

df_final = df_final.drop(['sys.sunrise','sys.sunset'], axis=1)

In [13]:
df_final.columns

Index(['weather_main', 'weather_description', 'visibility', 'timezone', 'id',
       'name', 'coord.lon', 'coord.lat', 'main.temp', 'main.feels_like',
       'main.temp_min', 'main.temp_max', 'main.pressure', 'main.humidity',
       'wind.speed', 'wind.deg', 'clouds.all', 'sys.country', 'main.sea_level',
       'main.grnd_level', 'wind.gust', 'date', 'sunrise', 'sunset'],
      dtype='object')

In [18]:
# Reemplazar NaN por None

import numpy as np

df_final = df_final.replace(np.nan,None)

In [19]:
df_final.head(5)

,weather_main,weather_description,visibility,timezone,id,name,coord.lon,coord.lat,main.temp,main.feels_like,...,wind.speed,wind.deg,clouds.all,sys.country,main.sea_level,main.grnd_level,wind.gust,date,sunrise,sunset
0,Clouds,few clouds,10000,7200,3117735,Madrid,-3.7026,40.4165,33.69,31.64,...,3.09,0,20,ES,None,None,None,2023-07-13 17:35:00,06:55:20,21:45:16
1,Clouds,few clouds,10000,7200,2509951,Valencia,-0.8333,39.3333,27.18,27.40,...,6.40,91,19,ES,1016.0,976.0,4.33,2023-07-13 17:35:42,06:47:05,21:30:33
2,Clouds,broken clouds,10000,7200,2521978,Alicante,-0.4815,38.3452,29.21,34.44,...,5.66,90,75,ES,None,None,None,2023-07-13 17:29:07,06:48:32,21:26:18
3,Clear,clear sky,10000,7200,2521883,Almeria,-2.3333,37.1667,28.88,29.06,...,4.03,115,0,ES,1017.0,933.0,3.8,2023-07-13 17:37:54,06:59:13,21:30:25
4,Clear,clear sky,10000,7200,2517115,Granada,-3.2500,37.2500,34.21,31.66,...,6.38,285,1,ES,1017.0,893.0,8.34,2023-07-13 17:32:56,07:02:40,21:34:19

In [23]:
df_final_work = df_final.rename(columns=lambda x: x.replace(".","_"))

In [24]:
df_final_work.columns

Index(['weather_main', 'weather_description', 'visibility', 'timezone', 'id',
       'name', 'coord_lon', 'coord_lat', 'main_temp', 'main_feels_like',
       'main_temp_min', 'main_temp_max', 'main_pressure', 'main_humidity',
       'wind_speed', 'wind_deg', 'clouds_all', 'sys_country', 'main_sea_level',
       'main_grnd_level', 'wind_gust', 'date', 'sunrise', 'sunset'],
      dtype='object')

In [19]:
# Generamos connexion a Big Query
from google.oauth2 import service_account # Para generar conexión con bq
bq_cred = service_account.Credentials.from_service_account_file('C:/Users/gabri/Documents/Developer/etl_weather/tfm-etl-weather-project-05b75b65d201.json')

In [25]:
# Enviamos el df a BigQuery

import pandas_gbq

pandas_gbq.to_gbq(df_final_work, 'data_warehouse.openweather', project_id='tfm-etl-weather-project', if_exists='replace',credentials=bq_cred)